name: crossq
channels:
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - cuda-nvcc=12.3.52
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.11.5
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - aiofiles==25.1.0
      - appdirs==1.4.4
      - attrs==25.4.0
      - cachetools==6.2.3
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - chex==0.1.90
      - click==8.3.1
      - cloudpickle==3.1.2
      - contourpy==1.3.3
      - cycler==0.12.1
      - cython==0.29.37
      - decorator==5.2.1
      - distrax==0.1.5
      - dm-env==1.6
      - dm-tree==0.1.9
      - docker-pycreds==0.4.0
      - etils==1.13.0
      - farama-notifications==0.0.4
      - fasteners==0.20
      - filelock==3.20.0
      - flax==0.7.4
      - fonttools==4.61.1
      - fsspec==2025.12.0
      - gast==0.7.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - glfw==2.10.0
      - google-auth==2.43.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.74.0
      - gymnasium==0.29.1
      - humanize==4.14.0
      - idna==3.11
      - imageio==2.31.3
      - importlib-resources==6.5.2
      - jax==0.4.19
      - jaxlib==0.4.19+cuda12.cudnn89
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - mpmath==1.3.0
      - msgpack==1.1.2
      - mujoco==2.3.7
      - mujoco-py==2.1.2.14
      - nest-asyncio==1.6.0
      - networkx==3.6.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.9.1.4
      - nvidia-cuda-cupti-cu12==12.9.79
      - nvidia-cuda-nvcc-cu12==12.9.86
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.9.79
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.4.1.4
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.7.5.82
      - nvidia-cusparse-cu12==12.5.10.65
      - nvidia-nccl-cu12==2.28.9
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.3.1
      - opt-einsum==3.4.0
      - optax==0.1.7
      - orbax-checkpoint==0.11.31
      - packaging==25.0
      - pandas==2.3.3
      - pathtools==0.1.2
      - pillow==12.0.0
      - protobuf==4.25.8
      - psutil==7.1.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pygments==2.19.2
      - pyopengl==3.1.10
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rich==13.5.2
      - rlax==0.1.6
      - rsa==4.9.1
      - sbx-rl==0.8.0
      - scipy==1.11.4
      - sentry-sdk==2.47.0
      - setproctitle==1.3.7
      - shimmy==1.3.0
      - simplejson==3.20.2
      - six==1.17.0
      - smmap==5.0.2
      - stable-baselines3==2.1.0
      - sympy==1.14.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorflow-probability==0.21.0
      - tensorstore==0.1.80
      - toolz==1.1.0
      - torch==2.1.2
      - tqdm==4.66.1
      - triton==2.1.0
      - typing-extensions==4.5.0
      - tzdata==2025.3
      - urllib3==2.6.2
      - wandb==0.15.10
      - werkzeug==3.1.4
      - wrapt==2.0.1
      - zipp==3.23.0
